datasource = [
  {
    name: 'angry'
    severity: -3
    datetime: '2018-02-11T20:17:59+3:00'
    type: 'mood'
  }
  {
    name: 'nervous'
    severity: -8
    datetime: '2018-02-13T13:17:59+3:00'
    type: 'mood'
  }
  {
    name: 'happy'
    severity: 2
    datetime: '2018-02-14T22:10:59+3:00'
    type: 'mood'
  }
  {
    name: 'nervous'
    severity: -9
    datetime: '2018-02-17T12:17:59+3:00'
    type: 'mood'
  }
  {
    name: 'ate'
    severity: 0
    datetime: '2018-02-17T22:00:59+3:00'
    type: 'event'
  }
  {
    name: 'took advil'
    severity: 0
    datetime: '2018-02-13T02:17:59+3:00'
    type: 'event'
  }
  {
    name: 'swim class'
    severity: 0
    datetime: '2018-02-11T20:17:59+3:00'
    type: 'event'
  }
]
chart = new (tauCharts.Chart)(
  data: datasource
  type: 'line'
  x: 'datetime'
  y: 'severity'
  split: 'type'
  size: null
  plugins: [
    tauCharts.api.plugins.get('tooltip')()
    tauCharts.api.plugins.get('legend')()
    tauCharts.api.plugins.get('quick-filter')()
    tauCharts.api.plugins.get('trendline')()
  ]
  guide: showAnchors: 'always')
chart.renderTo '#container'

# ---
# generated by js2coffee 2.2.0